#ifndef __CaptionsMyFrame__
#define __CaptionsMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "MyFrame.h"

//// end generated include

/** Implementing MyFrame */
class CaptionsMyFrame : public MyFrame
{
	protected:
		// Handlers for MyFrame events.
		void m_btnChooseDirectoryOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		CaptionsMyFrame( wxWindow* parent );
	//// end generated class members
		std::string getExifData(const std::string& filepath);
		std::string getIptcData(const std::string& filepath);



};

#endif // __CaptionsMyFrame__
