#ifndef __CaptionsMyFrame__
#define __CaptionsMyFrame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "MyFrame.h"

//// end generated include

/** Implementing MyFrame */
class CaptionsMyFrame : public MyFrame
{
	public:
		/** Constructor */
		CaptionsMyFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __CaptionsMyFrame__
